server:
  port: 7015
spring:
  application:
    name: micro-consumer-user-webclient
  cloud:
    config:
      enabled: false
eureka:
  client:
    service-url:
      defaultZone: http://dante:iamdante@${eureka.host:localhost}:${eureka.port:8761}/eureka/
management:
  endpoint:
    features:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
        - info
        - health
        - features