server:
  port: 7011
spring:
  application:
    name: micro-consumer-user
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
eureka:
  client:
    service-url:
      defaultZone: http://dante:iamdante@${eureka.host:localhost}:${eureka.port:8761}/eureka/

## 配置服务调用方的 Service Name
loadbalancer: 
  client: 
    name: MICRO-PROVIDER-USER