server:
  port: 7011
spring:
  application:
    name: micro-consumer-user
eureka:
  client:
    service-url:
      defaultZone: http://dante:iamdante@${eureka.host:localhost}:${eureka.port:8761}/eureka/
# 配置文件的优先级高于代码自定义@RibbonClient
micro-provider-user:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.ZoneAvoidanceRule
micro-provider-user2:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
# feign hystrix 请求的默认超时时间是1秒，这里修改为5秒，解决第一次调用超时的问题
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 5000