eureka:
  client:
    enabled: false
spring:
  cloud:
    gateway:
      routes:
      - id: retry_route
        uri: http://localhost:8101
        predicates:
        - Path=/retry/**
        filters:
        - name: Retry
          args:
            retries: 3
            statuses: FAILED_DEPENDENCY
          