eureka:
  client:
    enabled: false
spring:
  cloud:
    gateway:
      default-filters:
      - AddRequestHeader=X-DANTE-REQ, Cry
      - AddResponseHeader=X-DANTE-RESP, Devil
      - AddRequestParameter=X-NAME, Coder
      
      routes:
      - id: hystrix_route
        uri: http://localhost:8101
        predicates:
        - Path=/**
        filters:
        - name: Hystrix
          args:
            name: dockerfallbackcmd
            fallbackUri: forward:/fallback  ## 目前只支持 forward
        order: -1

## hystrix 超时触发时间
hystrix.command.dockerfallbackcmd.execution.isolation.thread.timeoutInMilliseconds: 2000    