eureka:
  client:
    service-url:
      defaultZone: http://dante:iamdante@${eureka.host:localhost}:${eureka.port:8761}/eureka/
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
          route-id-prefix: SPIRIT_
      routes:
      - id: provider-user
        uri: lb://MICRO-PROVIDER-USER   ## 最好大写
        predicates:
        - Path=/provider/**
        filters:
        - StripPrefix=1
          
         
          