eureka:
  client:
    enabled: false
spring:
  cloud:
    gateway:
      routes:
      - id: svc_1
        uri: http://localhost:8101/docker
        predicates:
        - Path=/svc
        - Weight=docker-svc, 85
      
      - id: svc_2
        uri: http://localhost:8102/docker
        predicates:
        - Path=/svc
        - Weight=docker-svc, 15