spring:
  profiles:
    active: strip
  cloud:
    config:
      enabled: false
management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
        - info
        - health
        - metrics
        - gateway