#!/usr/bin/env bash

POSTFIX="svc.cluster.local"
EUREKA_HOST_NAME="$MY_POD_NAME.$MY_INNER_SERVICE.$MY_POD_NAMESPACE.$POSTFIX"
export EUREKA_HOST_NAME=$EUREKA_HOST_NAME
REGISTER_USER="$EUREKA_USER"
REGISTER_PWD="$EUREKA_PWD"
BOOL_REGISTER="false"
BOOL_FETCH="false"

if [ $EUREKA_REPLICAS == 1 ]; then
	EUREKA_URL_LIST="http://$EUREKA_HOST_NAME:8761/eureka/,"
else 
	BOOL_REGISTER="true"
	BOOL_FETCH="true"
	for ((i=0; i<$EUREKA_REPLICAS; i ++))
    do
    	if [ $MY_POD_NAME != "$EUREKA_APPLICATION_NAME-$i" ]; then
	        temp="http://$REGISTER_USER:$REGISTER_PWD@$EUREKA_APPLICATION_NAME-$i.$MY_INNER_SERVICE.$MY_POD_NAMESPACE.$POSTFIX:8761/eureka/,"
	        EUREKA_URL_LIST="$EUREKA_URL_LIST$temp"
        fi
    done
fi

EUREKA_URL_LIST=${EUREKA_URL_LIST%?}
echo "EUREKA_URL_LIST is $EUREKA_URL_LIST"
export EUREKA_URL_LIST=$EUREKA_URL_LIST
export BOOL_FETCH=$BOOL_FETCH
export BOOL_REGISTER=$BOOL_REGISTER
export REGISTER_USER=$REGISTER_USER
export REGISTER_PWD=$REGISTER_PWD

java $JAVA_OPTS -Djava.security.egd=file:/dev/./urandom -jar app.jar