apiVersion: v1
kind: Service
metadata:
  name: eureka-svc-internal
  labels:
    app: eureka-svc-internal
  namespace: spiritdev
spec:
  clusterIP: None
  ports:
  - port: 8761
    name: server
  selector:
    app: eureka
      
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: eureka-pdb
  namespace: spiritdev
spec:
  selector:
    matchLabels:
      app: eureka
  minAvailable: 1

---
apiVersion: apps/v1
kind: StatefulSet
metadata: 
  name: eureka
  namespace: spiritdev
spec: 
  selector: 
    matchLabels:
      app: eureka
  serviceName: eureka-svc-internal
  replicas: "3"
  template:
    metadata:
      labels:
        app: eureka
    spec:
      terminationGracePeriodSeconds: 10
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 80
              podAffinityTerm: 
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - eureka
                topologyKey: kubernetes.io/hostname
      containers:
        - name: eureka-cluster
          image: harbor.xiaohehe.com/spiritdev/eureka-cluster:v1
          imagePullPolicy: IfNotPresent
          imagePullSecrets:
            - name: spiritdev-pushsecret-harbor-xiaohehe-com    ## 设置推送权限（可选）
          ports: 
            - containerPort: 8761
              name: server
              protocol: TCP
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              cpu: 500m
              memory: 1Gi
          env: 
            - name: MY_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: MY_INNER_SERVICE
              value: eureka-svc-internal
            - name: EUREKA_APPLICATION_NAME
              value: eureka
            - name: EUREKA_REPLICAS
              value: "3"
            - name: EUREKA_USER
              value: dante
            - name: EUREKA_PWD
              value: "123456"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8761
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8761
            initialDelaySeconds: 10
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: eureka-external-svc
  name: eureka-external-svc
spec:
  ports:
    - name: http-8761
      port: 8761
      protocol: TCP
      targetPort: 8761
  selector:
    app: eureka
  type: ClusterIP
              