server:
  port: 7061
spring:
  application:
    name: micro-consumer-user-feign-hystrix
eureka:
  client:
    service-url:
      defaultZone: http://dante:iamdante@${eureka.host:localhost}:${eureka.port:8761}/eureka/
# feign hystrix 请求的默认超时时间是1秒，这里修改为5秒，解决第一次调用超时的问题
#hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 5000
ribbon: 
  ReadTimeout: 10000
  ConnectTimeout: 10000
logging:
  level:
    org.dante.springcloud.feignclient.UserFeignClient: DEBUG
    org.dante.springcloud.feignclient.EurekaFeignConfigClient: DEBUG