--- 
# 配置management.port，eureka.instance.metadata-map.management.port=${management.port:8081}
management:
  server: 
    port: 10000
server:
  port: 7065
  servlet:
    context-path: /cusfig
spring:
  application:
    name: micro-consumer-user-feign-hystrix4
eureka:
  instance:
    prefer-ip-address: true
    metadata-map:
      management.port: ${management.port:7065}
      cluster: USER
  client:
    service-url:
      defaultZone: http://dante:iamdante@${eureka.host:localhost}:${eureka.port:8761}/eureka/
# feign hystrix 请求的默认超时时间是1秒，这里修改为5秒，解决第一次调用超时的问题
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 5000
logging:
  level:
    org.dante.springcloud.feignclient.UserFeignClient: DEBUG
    org.dante.springcloud.feignclient.EurekaFeignConfigClient: DEBUG