server:
  port: 8777
spring:
  application:
    name: eureka-client-exclude-jersey
eureka:
  client:
    service-url:
      defaultZone: http://dante:iamdante@${eureka.host:localhost}:${eureka.port:8761}/eureka/