server:
  port: ${config.port:8888}
spring:
  cloud:
    config:
      server:
        git:
          uri: https://git.oschina.net/dante7qx/oschina-config-repo
          username: dante
          password: Dante@2012
encrypt:
  key: config.foo