server:
  port: ${config.port:8888}
spring:
  cloud:
    config:
      server:
        git:
          uri: file://Users/dante/Documents/Project/spring/microservice/config-repo
encrypt:
  key: config.foo