server:
  port: ${config.port:8888}
spring:
  cloud:
    config:
      server:
        native:
          search-locations: file:////Users/dante/Documents/Project/spring/microservice/config-repos
encrypt:
  key: config.foo