server:
  port: ${config.port:8888}
spring:
  cloud:
    config:
      server:
        git:
          uri: file://Users/dante/Documents/Project/spring/microservice/config-repo
  rabbitmq:
    host: 10.71.174.111
    port: 5672
    username: dante
    password: 123456
    virtual-host: /springcloudbus
logging:
  level:
    com.netflix.discovery.TimedSupervisorTask: off