server:
  port: 6789
spring:
  application:
    name: micro-sidecar
sidecar:
  port: 3000
  health-uri: http://localhost:3000/health.json
eureka: 
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://dante:iamdante@${eureka.host:localhost}:${eureka.port:8761}/eureka/
