server:
  port: 8881
spring:
  application:
    name: micro-consumer-user-zuul
eureka:
  client:
    service-url:
      defaultZone: http://dante:iamdante@${eureka.host:localhost}:${eureka.port:8761}/eureka/
# feign hystrix 请求的默认超时时间是1秒，这里修改为5秒，解决第一次调用超时的问题
#hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 5000
zuul:
  ribbon-isolation-strategy: thread
  thread-pool:
    use-separate-thread-pools: true
    thread-pool-key-prefix: zuulgw
  ignored-services: '*'
  routes:
    micro-provider-user: 
      path: /zuul_user/**
      custom-sensitive-headers: false

management:
  security:
    enabled: false    