kind: Service
apiVersion: v1
metadata:
  name: cloud-k8s-consumer-service
  namespace: dante
spec:
  selector:
    app: cloud-k8s-consumer-service
  ports:
  - protocol: TCP
    port: 8080
    nodePort: 30030
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-k8s-consumer-service
  namespace: dante
spec:
  selector:
    matchLabels:
      app: cloud-k8s-consumer-service
  replicas: 1
  template:
    metadata:
      labels:
        app: cloud-k8s-consumer-service
    spec:
      containers:
      - name: cloud-k8s-consumer-service
        image: spirit/cloud-k8s-consumer-service:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: server_port
          value: "8080"
        - name: spring_cloud_kubernetes_ribbon_mode
          value: "pod"
        - name: feign_hystrix_enabled
          value: "true"