server:
  port: 8882

spring:
  application:
    name: micro-zuul-fileupload
  http:
    encoding:
      force-response: true
eureka:
  client:
    service-url:
      defaultZone: http://dante:iamdante@${eureka.host:localhost}:${eureka.port:8761}/eureka/
zuul:
  routes:
    micro-provider-user2: /u2/**
    micro-provider-user3: /zuul_file/**
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000
ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000