spring:
  application:
    name: micro-eureka-cluster
security:
  user:
    name: dante
    password: iamdante
    
--- 
spring:
  profiles: peer1
server:
  port: 8761
eureka: 
  server:
    enable-self-preservation: false # 关闭自我保护模式
  instance:
    hostname: peer1
    prefer-ip-address: true # 猜测主机名时，优先选择ip。默认为false，使用hostname作为主机名
  client:
    service-url:
      defaultZone: http://${security.user.name}:${security.user.password}@peer2:8762/eureka/

--- 
spring:
  profiles: peer2
server:
  port: 8762
eureka: 
  server:
    enable-self-preservation: false # 关闭自我保护模式
  instance:
    hostname: peer2
    prefer-ip-address: true # 猜测主机名时，优先选择ip。默认为false，使用hostname作为主机名
  client:
    service-url:
      defaultZone: http://${security.user.name}:${security.user.password}@peer1:8761/eureka/
