server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: file://Users/dante/Documents/Project/spring/microservice/config-repo
          username: dante
          password: Dante@2012
encrypt:
  keyStore:
    location: classpath:/server.jks
    password: letmein
    alias: mytestkey
    secret: changeme